### ISSUE TITLE
DecodeException when header contains array？

### ISSUE THREAD

**Issue by MIkeeJY** [auth0/JWTDecode.Android#88]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/JWTDecode.Android#readme) and [Examples](https://github.com/auth0/JWTDecode.Android/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://javadoc.io/doc/com.auth0.android/jwtdecode/latest/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/JWTDecode.Android/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

eyJhbGciOiJSUzI1NiIsIng1YyI6WyJNSUlGYnpDQ0JGZWdBd0lCQWdJUkFLZGZxUmlyMjF1ZUNpWXloVFIxcS9Zd0RRWUpLb1pJaHZjTkFRRUxCUUF3UmpFTE1Ba0dBMVVFQmhNQ1ZWTXhJakFnQmdOVkJBb1RHVWR2YjJkc1pTQlVjblZ6ZENCVFpYSjJhV05sY3lCTVRFTXhFekFSQmdOVkJBTVRDa2RVVXlCRFFTQXhSRFF3SGhjTk1qUXdNVEk1TURrd09USTJXaGNOTWpRd05ESTRNRGt3T1RJMVdqQWRNUnN3R1FZRFZRUURFeEpoZEhSbGMzUXVZVzVrY205cFpDNWpiMjB3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRHdraTV1ay9MUlRzbkQvMTFNNFcwUjY3VmhLOS9RY21NWTZQVFBaQ3AvRDNoS3RMSkNxb0YrNHM3VUVuTzFncSt6Wm5neEV3RUw0NU14anFRTS9JOW5adENtRFRQVDNnajg5aTFBN2M2RHo4L1U4RlE4SFlHZk1kM2d0U0N0TzM0bHVCTXZpSkhNRlgvenhpbXlwZERjR2d3VzcvTUc0aGQ4OUdzb2o1S3Npc3hZdTRwYmZPbjFJTmdXQ2t6cENrbmtpUlRONkZOSlNDcVlnT0ZuYWJiU3gvTndMRkp0UU12VDcvQmhjSXVJaXRkM1h4QmtTbThHbjZWSjhrdVA3ZVo5WWJ5akpMeEdURW5tVnlCYTl3NldCYlFLajJ0OWJYL0NwR0RlUkhpTU5pOUlPenhib3BHVEg2SC83SXZLc1FiNmV6OXZVekZkQXZsTG9DZDUwK1hCQWdNQkFBR2pnZ0ovTUlJQ2V6QU9CZ05WSFE4QkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUlLd1lCQlFVSEF3RXdEQVlEVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRFRmdRVVhDeisrOUU2Tk90eEE5a2FtSHMwZW5YaWFjb3dId1lEVlIwakJCZ3dGb0FVSmVJWURySlhrWlFxNWRSZGhwQ0QzbE96dUpJd2V3WUlLd1lCQlFVSEFRRUViekJ0TURnR0NDc0dBUVVGQnpBQmhpeG9kSFJ3T2k4dmIyTnpjQzV3YTJrdVoyOXZaeTl6TDJkMGN6RmtOR2x1ZEM4eWJFZFlNSFZUVVhKUVRUQXhCZ2dyQmdFRkJRY3dBb1lsYUhSMGNEb3ZMM0JyYVM1bmIyOW5MM0psY0c4dlkyVnlkSE12WjNSek1XUTBMbVJsY2pBZEJnTlZIUkVFRmpBVWdoSmhkSFJsYzNRdVlXNWtjbTlwWkM1amIyMHdJUVlEVlIwZ0JCb3dHREFJQmdabmdRd0JBZ0V3REFZS0t3WUJCQUhXZVFJRkF6QS9CZ05WSFI4RU9EQTJNRFNnTXFBd2hpNW9kSFJ3T2k4dlkzSnNjeTV3YTJrdVoyOXZaeTluZEhNeFpEUnBiblF2V0RKS01raHlYemRRYVUwdVkzSnNNSUlCQkFZS0t3WUJCQUhXZVFJRUFnU0I5UVNCOGdEd0FIVUFTTERqYTlxbVJ6UVA1V29DK3AwdzZ4eFNBY3RXM1N5QjJidS9xem5ZaEhNQUFBR05WTElERkFBQUJBTUFSakJFQWlCbFdxdWY2UDg3TC9zOFpvVXVoTzBzeEwvUVAxai9zNEY5SzUwd1gvNEZRd0lnWEx3U1hRQ0pZcGMxTDVJNE90dmdaVElaRDliUlRJaFE2VDd3UTV4WWFqNEFkd0R1emRCazFkc2F6c1ZjdDUyMHpST2lNb2RHZkx6czNzTlJTRmxHY1IrMW13QUFBWTFVc2dMd0FBQUVBd0JJTUVZQ0lRRGJDMHBDY1ZjVDJ2UHkzQzlKL1NJdHVsb1RDSzAxNGVmMjErVjNnWUVqVlFJaEFJdXBkaVZoeTIxY2ExdE1UaENFL2RydXhsVTgwT2RQd2xuTHV5Zm9OS09wTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCbVFDRDMreGZFSytUazRPOTBkN2Y3N2ZuQVAvaDQxSE53NkxlVzNGYVQ3UkcwQVRUNjc0M3NqdENPaFpkTU90MzFxaWZLdVFSN0craUtNcnFvZmpJVTNyTG1neGVObUhPb3hDVk9uMWNpR2J4Y25zL1lJcGtObGlCQmlwdjE0OGV2WVlQSWh0L1hqS0tPYXg3NkE0cmEyWFVIWHZXSTdZaDRtRnZJZENmWXdUUGN0R2Jnc2JtZTI2bkdKL1hoeG9uTmVNVjNtTENrbHRrL3MxZWM5YXlqNEgwZEc1QTdxUk1XeFdFb3dqQTNNbG5oSFBRM3ZZWENSZXREWTA4ZVJMNjVKZEFQN3RvZW4rR2t2N2FsWm80SlgzbWlycGROVkpzREI0b2tjMTlvMWx6ekltMWFWc0tRdEtaRi9yeCtpTysvRmpUYTRUVXducnNqME45SVdzRzYiLCJNSUlGakRDQ0EzU2dBd0lCQWdJTkFnQ09zZ0l6Tm1XTFpNM2JtekFOQmdrcWhraUc5dzBCQVFzRkFEQkhNUXN3Q1FZRFZRUUdFd0pWVXpFaU1DQUdBMVVFQ2hNWlIyOXZaMnhsSUZSeWRYTjBJRk5sY25acFkyVnpJRXhNUXpFVU1CSUdBMVVFQXhNTFIxUlRJRkp2YjNRZ1VqRXdIaGNOTWpBd09ERXpNREF3TURReVdoY05NamN3T1RNd01EQXdNRFF5V2pCR01Rc3dDUVlEVlFRR0V3SlZVekVpTUNBR0ExVUVDaE1aUjI5dloyeGxJRlJ5ZFhOMElGTmxjblpwWTJWeklFeE1RekVUTUJFR0ExVUVBeE1LUjFSVElFTkJJREZFTkRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS3ZBcXFQQ0UyN2wwdzl6QzhkVFBJRTg5YkEreFRtRGFHN3k3VmZRNGMrbU9XaGxVZWJVUXBLMHl2MnI2NzhSSkV4SzBIV0RqZXErbkxJSE4xRW01ajZyQVJaaXhteVJTamhJUjBLT1FQR0JNVWxkc2F6dElJSjdPMGcvODJxai92R0RsLy8zdDR0VHF4aVJoTFFuVExYSmRlQisyRGhrZFU2SUlneDZ3TjdFNU5jVUgzUmNzZWpjcWo4cDVTajE5dkJtNmkxRmhxTEd5bWhNRnJvV1ZVR08zeHRJSDkxZHNneTRlRktjZktWTFdLM28yMTkwUTBMbS9TaUttTGJSSjVBdTR5MWV1RkptMkpNOWVCODRGa3FhM2l2clhXVWVWdHllMENRZEt2c1kyRmthenZ4dHh2dXNMSnpMV1lIazU1emNSQWFjREEyU2VFdEJiUWZEMXFzQ0F3RUFBYU9DQVhZd2dnRnlNQTRHQTFVZER3RUIvd1FFQXdJQmhqQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3RWdZRFZSMFRBUUgvQkFnd0JnRUIvd0lCQURBZEJnTlZIUTRFRmdRVUplSVlEckpYa1pRcTVkUmRocENEM2xPenVKSXdId1lEVlIwakJCZ3dGb0FVNUs4ckpuRWFLMGduaFM5U1ppenY4SWtUY1Q0d2FBWUlLd1lCQlFVSEFRRUVYREJhTUNZR0NDc0dBUVVGQnpBQmhocG9kSFJ3T2k4dmIyTnpjQzV3YTJrdVoyOXZaeTluZEhOeU1UQXdCZ2dyQmdFRkJRY3dBb1lrYUhSMGNEb3ZMM0JyYVM1bmIyOW5MM0psY0c4dlkyVnlkSE12WjNSemNqRXVaR1Z5TURRR0ExVWRId1F0TUNzd0thQW5vQ1dHSTJoMGRIQTZMeTlqY213dWNHdHBMbWR2YjJjdlozUnpjakV2WjNSemNqRXVZM0pzTUUwR0ExVWRJQVJHTUVRd0NBWUdaNEVNQVFJQk1EZ0dDaXNHQVFRQjFua0NCUU13S2pBb0JnZ3JCZ0VGQlFjQ0FSWWNhSFIwY0hNNkx5OXdhMmt1WjI5dlp5OXlaWEJ2YzJsMGIzSjVMekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBZ0VBSVZUb3kyNGp3WFVyMHJBUGM5MjR2dVNWYktRdVl3M25MZmxMZkxoNUFZV0VlVmwvRHUxOFFBV1VNZGNKNm8vcUZaYmhYa0JIMFBOY3c5N3RoYWYyQmVvRFlZOUNrL2IrVUdsdWh4MDZ6ZDRFQmY3SDlQODRubnJ3cFIrNEdCRFpLK1hoM0kwdHFKeTJyZ09xTkRmbHI1SU1ROFpUV0EzeWx0YWt6U0JLWjZYcEYwUHBxeUNSdnAvTkNHdjJLWDJUdVBDSnZzY3AxL20ycFZUdHlCallQUlErUXVDUUdBSktqdE43UjVERnJmVHFNV3ZZZ1ZscENKQmt3bHU3KzdLWTNjVElmekU3Y21BTHNrTUtOTHVEeitSekNjc1lUc1ZhVTdWcDN4TDYwT1locUZrdUFPT3hEWjZwSE9qOStPSm1ZZ1BtT1Q0WDMrN0w1MWZYSnlSSDlLZkxSUDZuVDMxRDVubXNHQU9nWjI2LzhUOWhzQlcxdW85anU1ZlpMWlhWVlM1SDBIeUlCTUVLeUdNSVBoRldybHQvaEZTMjhOMXphS0kwWkJHRDNnWWdETGJpRFQ5ZkdYc3RwaytGbWM0b2xWbFdQelhlODF2ZG9FbkZicjVNMjcySGRnSldvK1doVDlCWU0wSmkrd2RWbW5SZmZYZ2xvRW9sdVROY1d6YzQxZEZwZ0p1OGZGM0xHMGdsMmliU1lpQ2k5YTZodlUwVHBwakp5SVdYaGtKVGNNSmxQcld4MVZ5dEVVR3JYMmwwSkR3UmpXLzY1NnIwS1ZCMDJ4SFJLdm0yWktJMDNUZ2xMSXBtVkNLM2tCS2tLTnBCTmtGdDhyaGFmY0NLT2I5SngvOXRwTkZsUVRsN0IzOXJKbEpXa1IxN1FuWnFWcHRGZVBGT1JvWm1Gek09IiwiTUlJRllqQ0NCRXFnQXdJQkFnSVFkNzBOYk5zMitScnFJUS9FOEZqVERUQU5CZ2txaGtpRzl3MEJBUXNGQURCWE1Rc3dDUVlEVlFRR0V3SkNSVEVaTUJjR0ExVUVDaE1RUjJ4dlltRnNVMmxuYmlCdWRpMXpZVEVRTUE0R0ExVUVDeE1IVW05dmRDQkRRVEViTUJrR0ExVUVBeE1TUjJ4dlltRnNVMmxuYmlCU2IyOTBJRU5CTUI0WERUSXdNRFl4T1RBd01EQTBNbG9YRFRJNE1ERXlPREF3TURBME1sb3dSekVMTUFrR0ExVUVCaE1DVlZNeElqQWdCZ05WQkFvVEdVZHZiMmRzWlNCVWNuVnpkQ0JUWlhKMmFXTmxjeUJNVEVNeEZEQVNCZ05WQkFNVEMwZFVVeUJTYjI5MElGSXhNSUlDSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQWc4QU1JSUNDZ0tDQWdFQXRoRUNpeDdqb1hlYk85eS9sRDYzbGFkQVBLSDlndmw5TWdhQ2NmYjJqSC83Nk51OGFpNlhsNk9NUy9rcjlySDV6b1Fkc2ZuRmw5N3Z1ZktqNmJ3U2lWNm5xbEtyK0NNbnk2U3huR1BiMTVsKzhBcGU2MmltOU1aYVJ3MU5FRFBqVHJFVG84Z1liRXZzL0FtUTM1MWtLU1VqQjZHMDBqMHVZT0RQMGdtSHU4MUk4RTNDd25xSWlydTZ6MWtaMXErUHNBZXduakh4Z3NIQTN5Nm1iV3daRHJYWWZpWWFSUU05c0hta2xDaXREMzhtNWFnSS9wYm9QR2lVVSs2RE9vZ3JGWllKc3VCNmpDNTExcHpycDFaa2o1WlBhSzQ5bDhLRWo4QzhRTUFMWEwzMmg3TTFiS3dZVUgrRTRFek5rdE1nNlRPOFVwbXZNclVwc3lVcXRFajVjdUhLWlBmbWdoQ042SjNDaW9qNk9HYUsvR1A1QWZsNC9YdGNkL3AyaC9yczM3RU9lWlZYdEwwbTc5WUIwZXNXQ3J1T0M3WEZ4WXBWcTlPczZwRkxLY3dacERJbFRpcnhaVVRRQXM2cXprbTA2cDk4ZzdCQWUrZERxNmRzbzQ5OWlZSDZUS1gvMVk3RHprdmd0ZGl6amtYUGRzRHRRQ3Y5VXcrd3A5VTdEYkdLb2dQZU1hM01kK3B2ZXo3VzM1RWlFdWErK3RneS9CQmpGRkZ5M2wzV0ZwTzlLV2d6N3pwbTdBZUtKdDhUMTFkbGVDZmVYa2tVQUtJQWY1cW9JYmFwc1pXd3Bia05GaEhheDJ4SVBFRGdmZzFhelZZODBaY0Z1Y3RMN1RsTG5NUS8wbFVUYmlTdzFuSDY5TUc2ek8wYjlmNkJRZGdBbUQwNnlLNTZtRGNZQlpVQ0F3RUFBYU9DQVRnd2dnRTBNQTRHQTFVZER3RUIvd1FFQXdJQmhqQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCVGtyeXNtY1JvclNDZUZMMUptTE8vd2lSTnhQakFmQmdOVkhTTUVHREFXZ0JSZ2UyWWFSUTJYeW9sUUwzMEV6VFNvLy96OVN6QmdCZ2dyQmdFRkJRY0JBUVJVTUZJd0pRWUlLd1lCQlFVSE1BR0dHV2gwZEhBNkx5OXZZM053TG5CcmFTNW5iMjluTDJkemNqRXdLUVlJS3dZQkJRVUhNQUtHSFdoMGRIQTZMeTl3YTJrdVoyOXZaeTluYzNJeEwyZHpjakV1WTNKME1ESUdBMVVkSHdRck1Da3dKNkFsb0NPR0lXaDBkSEE2THk5amNtd3VjR3RwTG1kdmIyY3ZaM055TVM5bmMzSXhMbU55YkRBN0JnTlZIU0FFTkRBeU1BZ0dCbWVCREFFQ0FUQUlCZ1puZ1F3QkFnSXdEUVlMS3dZQkJBSFdlUUlGQXdJd0RRWUxLd1lCQkFIV2VRSUZBd013RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQURTa0hyRW9vOUMwZGhlbU1Yb2g2ZEZTUHNqYmRCWkJpTGc5TlIzdDVQK1Q0VnhmcTd2cWZNL2I1QTNSaTFmeUptOWJ2aGRHYUpRM2IydDZ5TUFZTi9vbFVhenNhTCt5eUVuOVdwcktBU09zaElBckFveVpsK3RKYW94MTE4ZmVzc21YbjFoSVZ3NDFvZVFhMXYxdmc0RnY3NHpQbDYvQWhTcnc5VTVwQ1pFdDRXaTR3U3R6NmRUWi9DTEFOeDhMWmgxSjdRSlZqMmZoTXRmVEpyOXc0ejMwWjIwOWZPVTBpT015K3FkdUJtcHZ2WXVSN2haTDZEdXBzemZudzBTa2Z0aHMxOGRHOVpLYjU5VWh2bWFTR1pSVmJOUXBzZzNCWmx2aWQwbElLTzJkMXhvemNsT3pnalhQWW92SkpJdWx0emtNdTM0cVFiOVN6L3lpbHJiQ2dqOD0iXX0.eyJub25jZSI6ImN0dnpHQnFHQkorWThUNklWVTM2aXUyOEtzemVaTE5TVTJGbVpYUjVJRTVsZENCVFlXMXdiR1U2SURFM01USTJOVEkzTmpReE1EVT0iLCJ0aW1lc3RhbXBNcyI6MTcxMjY1Mjc3MDUxNiwiYXBrUGFja2FnZU5hbWUiOiJjb20uZmxpbmthcHBzLnNhZnRleW5ldCIsImFwa0RpZ2VzdFNoYTI1NiI6IkpKdHlkZjVyblJ4YytTK1ZrSENBUVdKWVFxcDliL0FkYklhVjlZckRDcnM9IiwiY3RzUHJvZmlsZU1hdGNoIjpmYWxzZSwiYXBrQ2VydGlmaWNhdGVEaWdlc3RTaGEyNTYiOlsiRDN6MjZ3S1doL2RTTkdsczJqQU14MTFNa2YwOWVVcUFPWmFhM2xXKzVBMD0iXSwiYmFzaWNJbnRlZ3JpdHkiOnRydWUsImV2YWx1YXRpb25UeXBlIjoiQkFTSUMiLCJkZXByZWNhdGlvbkluZm9ybWF0aW9uIjoiVGhlIGFwcCBpcyBhbGxvd2xpc3RlZCB0byB1c2UgdGhlIFNhZmV0eU5ldCBBdHRlc3RhdGlvbiBBUEkgdW50aWwgdGhlIGZ1bGwgdHVybmRvd246IGh0dHBzOi8vZy5jby9wbGF5L3NhZmV0eW5ldC10aW1lbGluZS4ifQ.c7TsHcXTfFO57j9eQOPRNEMqab-YG-FLEZOQyPNZEg2rYHbjyqK46uU5x5ePbzXgYR0gh_gifoaySizVjzL-pl8CVz4FSdJ7aeSkQ4BYtV3kFprPiGormMU5Ze7tF39PwLvUDZoEzB7mev_LI73rZEcsF-_qdPeeOYWbozXRc_KF8knw5uLWaQfmFE_sHxa_7hIlmnLb-PGrWM_7X1tn9JfVrAToiRcKyyuXlo5OsfRVlodgmBupxgV5EDpxZ1PzgISph1HJE237-LTSmsDz0Yq94zekucfUbRwgOPR6XrPEDBWllKWTUQu7ffizgRHDtqwusgT3vWAIfpgpA__Gvg                   

this jwt token cuz it！

### Reproduction

    JWT jwt = new JWT(jwsResult);            
   Caused by: com.auth0.android.jwt.DecodeException: The token's payload had an invalid JSON format.
                                                                                                    	at com.auth0.android.jwt.JWT.parseJson(JWT.java:247)
                                                                                                    	at com.auth0.android.jwt.JWT.decode(JWT.java:213)
                                                                                                    	at com.auth0.android.jwt.JWT.<init>(JWT.java:40)

### JWTDecode.Android version

2.0.2

### Android version(s)

13

**Comment by MIkeeJY** [comment]
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 23 path $.
                                                                                                    	at com.google.gson.Gson.fromJson(Gson.java:1238)
                                                                                                    	at com.google.gson.Gson.fromJson(Gson.java:1137)
                                                                                                    	at com.google.gson.Gson.fromJson(Gson.java:1047)
                                                                                                    	at com.google.gson.Gson.fromJson(Gson.java:1014)
                                                                                                    	at com.auth0.android.jwt.JWT.parseJson(JWT.java:245)
                                                                                                    	at com.auth0.android.jwt.JWT.decode(JWT.java:213) 
                                                                                                    	at com.auth0.android.jwt.JWT.<init>(JWT.java:40) 
                                                                                                    	at com.flinkapps.safteynet.hook.MainActivity.onCreate(MainActivity.java:60) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8290) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8269) 
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384) 
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657) 
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7898) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
                                                                                                    Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 23 path $.
                                                                                                    	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:836)
                                                                                                    	at com.google.gson.internal.bind.TypeAdapters$15.read(TypeAdapters.java:421)
                                                                                                    	at com.google.gson.internal.bind.TypeAdapters$15.read(TypeAdapters.java:409)
                                                                                                    	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
                                                                                                    	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:186)
                                                                                                    	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:144)
                                                                                                    	at com.google.gson.Gson.fromJson(Gson.java:1227)
                                                                                                    	at com.google.gson.Gson.fromJson(Gson.java:1137) 
                                                                                                    	at com.google.gson.Gson.fromJson(Gson.java:1047) 
                                                                                                    	at com.google.gson.Gson.fromJson(Gson.java:1014) 
                                                                                                    	at com.auth0.android.jwt.JWT.parseJson(JWT.java:245) 
                                                                                                    	at com.auth0.android.jwt.JWT.decode(JWT.java:213) 
                                                                                                    	at com.auth0.android.jwt.JWT.<init>(JWT.java:40) 
                                                                                                    	at com.flinkapps.safteynet.hook.MainActivity.onCreate(MainActivity.java:60) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8290) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8269) 
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384) 
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657) 
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7898) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by pmathew92** [comment]
We have fixed this in [2.1.0](https://github.com/auth0/JWTDecode.Android/releases/tag/2.1.0) version of the SDK. Please try this and let us know
